feat(relayer): Introduce VaraArgs with retries count
gear-tech/gear-bridges pull request #184
Opened 2024-10-31 04:49 UTC by gshep

Resolves #145 

@gear-tech/dev

2024-10-31 04:54 UTC, gshep commented
We may also address the TODO to `VaraEndpointArgs` within that PR

2024-10-31 06:02 UTC, mertwole reviewed
Please also introduce it in `gear-rpc-client`

2024-10-31 06:02 UTC, mertwole commented
> We may also address the TODO to `VaraEndpointArgs` within that PR

I think it fits great into this PR

2024-10-31 12:33 UTC, mertwole requested changes

2024-10-31 12:33 UTC, mertwole commented on relayer/src/main.rs
> +async fn create_gear_client(domain: &str, port: u16, retries: u8) -> GearApi {
```suggestion
async fn create_gear_client(args: &VaraArgs) -> GearApi {
```

2024-10-31 12:33 UTC, mertwole commented on relayer/src/main.rs
> +    vara_suri: String,
I think it should be in a separate struct as it's required not by every relayer

2024-10-31 12:33 UTC, mertwole commented on tools/genesis-config/src/main.rs
> +    gear_rpc_retries: u8,
I think somethig like `const GEAR_RPC_RETRIES = 3` will be ok for this use-case

2024-11-01 13:59 UTC, mertwole commented on relayer/src/main.rs
> +    vara: VaraArgs,
```suggestion
    vara_args: VaraArgs,
```

2024-11-01 13:59 UTC, mertwole commented on relayer/src/main.rs
> +    vara: VaraArgs,
```suggestion
    vara_args: VaraArgs,
```

2024-11-01 14:01 UTC, mertwole approved these changes

2024-11-01 15:39 UTC, merged